---
title: "Homework 7 -- Intro to Probability and Statistics"
author: "Your name here"
output: pdf_document
---

# Instructions:

**Due:** 05/28 at 11:59PM.

**What am I expecting?** An R Markdown with the answers.

**Have fun!**

## Question 1

An urn has two white balls (W) and three red balls (R). You draw a ball from the urn. If it is white, you flip a coin. If it is red, you throw it back in the urn and draw another ball. What is the sample space of this experiment?

The sample space is U = (W, head), (W, tail), (R)

## Question 2

Suppose you toss two dices. Consider two events:

- A: the sum of the numbers in both dices is equal to 9
- B: the number in the first die is greater than or equal 4.

Define:

1. The elements of $A$
A: (3,6), (6, 3), (5, 4), (4, 5)
2. The elements of $B$
B: (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1) (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)
3. The elements of $A \cap B$
$A \cap B$: (6, 3), (5, 4), (4, 5)
4. The elements of $A \cup B$
$A \cup B$: (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1) (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (3, 6)
5. The elements of $A^C$
(3,6)

## Question 3

The probability that student $A$ solves a given problem is $\dfrac{2}{3}$. The probability that student $B$ solves the same problem is $\dfrac{3}{4}$. If both try to solve the problem independently, what is the chance that the problem will be solved?

1/4 * 1/3 = 1/12 -> Probability of none of them solving the problem

1 - 1/12 = 11/12 -> Probability of the problem be solved

```{r}
11/12
```

There is a probability of 11 in 12, 91,67%


## Question 4

Consider the following probability table:

|       | $B$  | $B^C$ | Total |
|-------|------|-------|-------|
| $A$   | 0.04 | 0.06  | 0.10  |
| $A^C$ | 0.08 | 0.82  | 0.90  |
| Total | 0.12 | 0.88  | 1.00  |

Note that $P(A) = 0.10$, $P(A \cap B) = 0.04$, and so on. Are the events $A$ and $B$ independent?

P(A) = 0.10 
P(B) = 0.12
P(AandB) = 0.04



Independet events: $P(A \cap B)$ = $P(A)$*$P(B)$
0.1 x 0.12  = 0,012

The events are dependent

## Question 5

A company produces phones in three factories. In factory I, the company produces 40\% of the phones, while in factories II and III produce 30\% of the phones in each. The chance of a phone is assembled broken is 0.01 (factory I), 0.04 (factory II), and 0.03 (factory III). The phones are then taken to a warehouse. 

1. If you select a phone randomly in the warehouse, what is the chance that it is broken?

I) 1% in 40%
0,01*0,4 = 0,004

II) 4% in 30%
0,04*0,3 = 0,012

III) 3% in 30%
0,03*0,3 = 0,009

P(I) + P(II) + P(III) 

0,004 + 0,012 + 0,009 = 0,025

There is a 2,5% chance of picking a broken phone


2. Suppose the phone you draw is broken. What is the probability that it was manufactured by factory I?

0,004 in 0,025 = 0,16

16% of the borken phone being manufactured by factory I


## Question 6

Prove that if $A$ and $B$ are independent, then:

1. $A^C$ and $B^C$ are independent.
-$P(A\cap B) + P(A^C) = P(A) = 1$
-$P(A\cap B) + P(B^C) = P(B) = 1$
-$P(A) * P(B) = P(A\cap B)$
-$[P(A) * P(B)] / P(A\cap B)  = P(A\cap B) / P(A\cap B)$
-$P(A^C) * P(B^C) = 1 =P(A) * P(B) = P(A\cap B)$


2. $A$ and $B^C$ are independent.
Independent if $P(A \cap B^C) = P(A)*P(B^C)$
$$P(A^C) = 1 - P(A\cap B)$$
$$P(A) = P(A^C) + P(A \cap B)$$
$$P(A) = P(A^C) +  P(A) * P(B)$$
$$P(A^C) =  P(A) -  P(A) * P(B)$$
$$P(A^C) =  P(A)(1- P(B)) = P(A)P(B^C) = P(A \cap B^C)$$

3. $A^C$ and $B$ are independent.

$$P(B^C) = 1 - P(A \cap B)$$
$$P(B) = P(B^C) + P(A \cap B)$$
$$P(B) = P(B^C) +  P(A) * P(B)$$
$$P(B^C) =  P(B) -  P(A) * P(B)$$
$$P(B^C) =  P(B)(1- P(A)) = P(B)P(A^C) = P(B \cap A^C)$$

## Question 7

Let $\bar{x} = \dfrac{\sum_{i=1}^n x_i}{n}$. Prove that:

1. $\sum_{i=1}^n(x_i-\bar{x}) = 0$
-$\sum_{i=1}^n(x_i- n\bar{x})$
-$\sum_{i=1}^nx_i - \sum_{i=1}^n n\bar{x})$
-$\sum_{i=1}^nx_i = \sum_{i=1}^n n\bar{x})$
-$\sum_{i=1}^nx_i = \sum_{i=1}^n n\dfrac{\sum_{i=1}^n x_i}{n}$
-$\sum_{i=1}^nx_i = x_i$
-$\sum_{i=1}^nx_i - x_i = 0$


2. $\sum_{i=1}^n(x_i-\bar{x})^2 = \sum_{i=1}^n x_i^2 - n\bar{x}^2$
- $\sum_{i=1}^nx_i^2-2x_i\bar{x} +\bar{x}^2$
-$\sum_{i=1}^nx_i^2-2n\bar{x} +n\bar{x}^2 = \sum_{i=1}^n x_i^2 - n\bar{x}^2$

## Question 8

Let $P(k; n,p) = {n \choose k} p^k(1-p)^{n-k}$ the probability of $k$ successes in a binomial distribution with $n$ trials $p$ probability of success. Prove that:

$$ P(k+1; n,p) \ = \ \dfrac{(n-k)p}{(k+1)(1-p)}P(k; n,p) $$
$$\dfrac{P(k+1; n,p)}{P(k; n,p)} \ = \ \dfrac{(n-k)p}{(k+1)(1-p)}$$
$$\dfrac{{n \choose k+1} p^{k+1}(1-p)^{n-k+1}}{{n \choose k} p^k(1-p)^{n-k}}$$
$$\dfrac{\dfrac{n!}{(k+1)!(n-k-1)!} p^{k+1}(1-p)^{n-k+1}}{\dfrac{n!}{k!(n-k)!} p^k(1-p)^{n-k}}$$
$$\dfrac{(n-k)}{(k+1)} p \dfrac{1}{(1-p)}$$
$$\dfrac{(n-k)p}{(k+1)(1-p)}$$

